http://localhost:8080/add?string=1
###
http://localhost:8080/add?string=2
###
http://localhost:8080/add?string=3
###
http://localhost:8080/add?string=4
###
http://localhost:8080/add?string=5
###
http://localhost:8080/set?id=4&string=AA
###
http://localhost:8080/set?id=0&string=sss
###
http://localhost:8080/set?id=-1&string=666
###

http://localhost:8080/addindex?id=0&string=0
###

http://localhost:8080/removeid?id=0
###
http://localhost:8080/remove?string=A
###

http://localhost:8080/contains?string=3
###

http://localhost:8080/indexof?string=5
###
http://localhost:8080/lastindex?string=5
###
http://localhost:8080/get?id=2
###
http://localhost:8080/equals?list=1,2,3
###
http://localhost:8080/clear
###
http://localhost:8080/size
###

http://localhost:8080/empty
###

http://localhost:8080/new
###

http://localhost:8080/getAll